---
sudo: required
dist: xenial

language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.10.2
  - ANSIBLE_VERSION=2.10.1
  - ANSIBLE_VERSION=2.10.0
  - ANSIBLE_VERSION=2.9.14
  - ANSIBLE_VERSION=2.9.13
  - ANSIBLE_VERSION=2.9.12
  - ANSIBLE_VERSION=2.9.11
  - ANSIBLE_VERSION=2.9.10
  - ANSIBLE_VERSION=2.9.9
  - ANSIBLE_VERSION=2.9.8
  - ANSIBLE_VERSION=2.9.7
  - ANSIBLE_VERSION=2.9.6
  - ANSIBLE_VERSION=2.9.5
  - ANSIBLE_VERSION=2.9.4
  - ANSIBLE_VERSION=2.9.3
  - ANSIBLE_VERSION=2.9.2
  - ANSIBLE_VERSION=2.9.1
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.8.16
  - ANSIBLE_VERSION=2.8.15
  - ANSIBLE_VERSION=2.8.14
  - ANSIBLE_VERSION=2.8.13
  - ANSIBLE_VERSION=2.8.12
  - ANSIBLE_VERSION=2.8.11
  - ANSIBLE_VERSION=2.8.10
  - ANSIBLE_VERSION=2.8.9
  - ANSIBLE_VERSION=2.8.8
  - ANSIBLE_VERSION=2.8.7
  - ANSIBLE_VERSION=2.8.6
  - ANSIBLE_VERSION=2.8.5
  - ANSIBLE_VERSION=2.8.4
  - ANSIBLE_VERSION=2.8.3
  - ANSIBLE_VERSION=2.8.2
  - ANSIBLE_VERSION=2.8.1
  - ANSIBLE_VERSION=2.8.0

branches:
  only:
    - master

matrix:
  allow_failures:
    # https://github.com/ansible/ansible/issues/56674
    - env: ANSIBLE_VERSION=2.8.0

before_install:
  - sudo apt-get update -qq

  # Remove ufw
  - sudo apt-get remove --purge --yes ufw

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml; fi

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: "If2mqrqZs5q6yZ9bs9qq+pmgCEMCTv1Nk3vQjax9N+xFoIvnRi1v0drEekibKgns8eg0Mg/Tya7xxXokqFhs3wVY64r43v86HFLS2MVDTaMYAxK3kRd4x8R5INIAN1U7Dtsk8RQbIngzGJPZwOfmOtY1qQ5p3RLMM+6zEBQOO7U="
